version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: monthly
      time: '13:00'
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 10
    reviewers:
      - RasaHQ/atom-squad
    labels:
      - type:dependencies
    ignore:
      - dependency-name: prompt-toolkit
        versions:
          - "> 2.0.10"
      - dependency-name: pytest-asyncio
        versions:
          - "> 0.10.0"
  - package-ecosystem: npm
    directory: "/docs"
    schedule:
      interval: monthly
      time: '13:00'
    pull-request-branch-name:
      separator: "-"
    # currently disabled because we cannot update the docs theme and its dependencies
    open-pull-requests-limit: 0
    reviewers:
      - "m-vdb"
    labels:
      - type:dependencies

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: '12:00'
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 10
    reviewers:
      - RasaHQ/infrastructure-squad
    labels:
      - type:dependencies
